apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-api.fullname" . }}
  labels:
    {{- include "front-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  FRONT_API_JWT_SECRET: {{ .Values.jwt.secret | quote }}
  FRONT_API_DEMO_PASSWORD: {{ .Values.demo.password | quote }}
