apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{ .Values.metadataPostgres.user }}:{{ .Values.metadataPostgres.password }}@{{ include "airflow.fullname" . }}-metadata-postgres:5432/{{ .Values.metadataPostgres.db }}"
  _AIRFLOW_WWW_USER_USERNAME: {{ .Values.webAdmin.username | quote }}
  _AIRFLOW_WWW_USER_PASSWORD: {{ .Values.webAdmin.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.weatherPostgres.password | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}
