spring.application.name=WeatherDataFetcher

app.s3.bucket-name=weather-raw
app.kafka.output-topic=weather.actual.raw.created
app.kafka.input-topic=weather.need_info
app.s3.endpoint=http://minio:9000
app.s3.access-key=minioadmin
app.s3.secret-key=minioadmin
app.external-api-url=http://historical-se26.bxkr.org/api/avg-temperature
