apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dm-trigger.fullname" . }}
  labels:
    {{- include "dm-trigger.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIRFLOW_API_PASSWORD: {{ .Values.airflow.password | quote }}
