apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analytics-api.fullname" . }}
  labels:
    {{- include "analytics-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}
