export const strings = {
  app: {
    name: "WeatherPulse",
  },
  landing: {
    pitch: "Отслеживайте, где и насколько сильно прогнозы погоды расходятся с реальностью.",
    signIn: "Войти",
    demo: "Демо-доступ",
  },
  login: {
    title: "Вход в систему",
    username: "Имя пользователя",
    password: "Пароль",
    submit: "Войти",
    back: "На главную",
    invalid: "Неверное имя пользователя или пароль",
    genericError: "Не удалось войти. Попробуйте ещё раз.",
  },
  nav: {
    dashboard: "Дашборд",
    topErrors: "Топ ошибок",
    explorer: "Регионы и станции",
    admin: "Администрирование",
    logout: "Выйти",
    demoBadge: "Демо-режим",
    theme: "Тема",
    menu: "Меню",
  },
  filters: {
    dateFrom: "Дата с",
    dateTo: "Дата по",
    regions: "Регионы",
    stations: "Станции",
    apply: "Применить",
    forecastMinDateHint:
      "Данные доступны за период с 2022-01-01 по 2026-06-30 — за пределами этого диапазона запрос может не загрузиться.",
  },
  async: {
    pending: "Запрашиваем недостающие данные, это может занять несколько минут…",
    failed: "Не удалось получить данные прогноза за этот период.",
    retry: "Повторить",
  },
  dashboard: {
    title: "Дашборд",
    rowsCount: "Число записей",
    temperatureMae: "MAE темп.",
    temperatureBias: "Смещение темп.",
    tempMinMae: "MAE мин. темп.",
    tempMinBias: "Смещение мин. темп.",
    tempMaxMae: "MAE макс. темп.",
    tempMaxBias: "Смещение макс. темп.",
    precipitationMae: "MAE осадков",
    precipitationBias: "Смещение осадков",
  },
  topErrors: {
    title: "Топ ошибок",
    metric: "Метрика",
    limit: "Лимит строк",
    columns: {
      wmoIndex: "Станция",
      day: "Дата",
      ingestedAt: "Загружено",
    },
    empty: "Нет данных за выбранный период.",
  },
  explorer: {
    title: "Регионы и станции",
    searchStation: "Поиск станции по названию или индексу",
    searchRegion: "Поиск региона по названию",
    regions: "Регионы",
    stations: "Станции",
    actualVsForecast: "Ошибка по времени (со знаком)",
    errorOverTime: "Абсолютная ошибка по времени",
    selectPrompt: "Выберите регион или станцию, чтобы увидеть график.",
  },
  admin: {
    title: "Администрирование",
    createUser: "Создать пользователя",
    columns: {
      username: "Имя пользователя",
      role: "Роль",
      active: "Активен",
      createdAt: "Создан",
      actions: "Действия",
    },
    resetPassword: "Сбросить пароль",
    deactivate: "Деактивировать",
    activate: "Активировать",
    deleteUser: "Удалить",
    modalCreateTitle: "Новый пользователь",
    modalResetTitle: "Сброс пароля",
    newPassword: "Новый пароль",
    save: "Сохранить",
    cancel: "Отмена",
    confirmDelete: "Удалить пользователя без возможности восстановления?",
    forbidden: "У вас нет доступа к этому разделу.",
  },
  roles: {
    admin: "Администратор",
    user: "Пользователь",
  },
  common: {
    loading: "Загрузка…",
    notFound: "Страница не найдена",
    close: "Закрыть",
  },
} as const;
